version: '3.4'
services:
 web:
  build: .
  ports:
   - "5555:5555"
  env_file: .env
  depends_on:
   - db
  volumes:
   - .:/usr/src/api
 db:
  image: mongo:latest
  ports:
   - "27017:27017"
  env_file: .env