version: '3.9'
services:
  api-showcase:
    build:
      context: .
    container_name: nodejs-api-showcase
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - DATABASE_URL=mongodb://db:27017/nodejsshowcase
    depends_on:
      - db
    volumes:
      - .:/home/nodejs/src
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    env_file: .env
volumes:
  mongodb:
