name: '[Api_Showcase] Running Tests on merging to Master Branch'

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies server
      run: | # run multiple commands
        npm ci
    - name: Run tests server
      run: npm run test
      env:
        APP_ENV: test
        DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
        HTTP_PORT: 8080
        JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}
        REDIS_URL: ${{ secrets.REDIS_URL }}